# Generated by Django 3.2.6 on 2023-11-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertrating',
            name='dissert',
        ),
        migrations.RemoveField(
            model_name='dissertrating',
            name='person',
        ),
        migrations.RemoveField(
            model_name='pastarating',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='pastarating',
            name='person',
        ),
        migrations.RemoveField(
            model_name='saladrating',
            name='person',
        ),
        migrations.RemoveField(
            model_name='saladrating',
            name='salad',
        ),
        migrations.RemoveField(
            model_name='snacksrating',
            name='person',
        ),
        migrations.RemoveField(
            model_name='snacksrating',
            name='snacks',
        ),
        migrations.DeleteModel(
            name='Dissert',
        ),
        migrations.DeleteModel(
            name='DissertRating',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.DeleteModel(
            name='PastaRating',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='SaladRating',
        ),
        migrations.DeleteModel(
            name='Snacks',
        ),
        migrations.DeleteModel(
            name='SnacksRating',
        ),
    ]
