# Generated by Django 3.2.6 on 2023-11-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0003_auto_20231114_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluateChoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appearance', models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='appearance')),
                ('taste', models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='taste')),
                ('healthiness', models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='healthiness')),
                ('familiarity', models.CharField(choices=[(None, ''), ('Strongly_Disagree', 'Strongly Disagree'), ('Disagree', 'Disagree'), ('Neutral', 'Neutral'), ('Agree', 'Agree'), ('Strongly_Agree', 'Strongly Agree')], default=None, max_length=100, verbose_name='familiarity')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(default=None, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_quality.personal_info')),
            ],
            options={
                'verbose_name': 'EvaluateChoices',
                'db_table': 'EvaluateChoices',
                'ordering': ['id'],
            },
        ),
    ]
